libpeony-qt/controls/directory-view/view/list-view/list-view.cpp
if we clearFocus method, then use shortcut key will not work.(#103)
=> if click at blank space,can' t use ctrl+A

translations/peony-qt/peony-qt_zh_CN.ts
Finish the Chinese expression of the word Undo and Redo
=> Finish the Chinese expression of the word Undo and Redo

.gitignore, libpeony-qt/file-operation/create-template-operation.cpp
由模板文件创建新文件时，更新了新建文件的访问时间和最近更新时间
=> change file's modify time and access time after copy templete file

peony-qt-desktop/desktop-icon-view.cpp
=> fix invert selection bug on desktop

libpeony-qt/windows/format_dialog.cpp, libpeony-qt/windows/format_dialog.h, libpeony-qt/windows/format_dialog.ui, translations/libpeony-qt/libpeony-qt_zh_CN.ts
add format processbar , add notify success or error while  format  finished.
=> add  processbar show format

libpeony-qt/file-utils.cpp, libpeony-qt/file-utils.h, libpeony-qt/model/side-bar-file-system-item.cpp, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [ADD] There is no normal pop-up U disk reminder

libpeony-qt/file-operation/file-operation-manager.cpp, libpeony-qt/file-operation/file-trash-operation.cpp
=> [FIX] block error when deleting recycle bin folder

libpeony-qt/file-enumerator.cpp
=> solve the mouse WaitCursor while enter file no permission denied

libpeony-qt/file-operation/file-move-operation.cpp
=> [FIX] cannot cut and paste current folder files

libpeony-qt/file-operation/file-operation-progress-bar.cpp, libpeony-qt/file-operation/file-operation-progress-bar.h, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> adjiust color

libpeony-qt/file-operation/file-operation-progress-bar.cpp, libpeony-qt/file-operation/file-operation-progress-bar.h, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
1. 根据设计需求，换了一个按钮图片
2. 增加了取消文件操作的弹框提醒
3. 修复了点中“其它队列”按钮晃动鼠标导致界面布局错误的问题
=> [ADD] change some button picture and add some tooltip

libpeony-qt/file-operation/file-operation-progress-bar.cpp
=> [FIX] progress widget compatible with lower version QT

libpeony-qt/file-operation/file-copy-operation.cpp, libpeony-qt/file-operation/file-delete-operation.cpp, libpeony-qt/file-operation/file-link-operation.cpp, libpeony-qt/file-operation/file-move-operation.cpp, libpeony-qt/file-operation/file-operation-error-dialog.cpp, libpeony-qt/file-operation/file-operation-error-dialog.h, libpeony-qt/file-operation/file-operation-error-handler.h, libpeony-qt/file-operation/file-operation-manager.cpp, libpeony-qt/file-operation/file-operation-manager.h, libpeony-qt/file-operation/file-operation.h, libpeony-qt/file-operation/file-rename-operation.cpp, libpeony-qt/file-operation/file-trash-operation.cpp, libpeony-qt/file-operation/file-untrash-operation.cpp
=> [FIX] file operation error handle

libpeony-qt/model/side-bar-file-system-item.cpp
fix bug:14671
1.add function get_object_from_block_device to get block.
2.while block ->type is iso9660 , eject the disc.
=> To reslove while disc device umount,the disc does not eject

libpeony-qt/file-operation/file-operation-progress-bar.cpp, libpeony-qt/file-operation/file-operation-progress-bar.h
=> change some widget size

libpeony-qt/controls/menu/side-bar-menu/side-bar-menu.cpp, libpeony-qt/windows/format_dialog.cpp
=> solve format_err and let filesystem cannot format

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp, peony-qt-desktop/desktop-menu.cpp
add thirdpart icon (for example:wps...) in context menu ->new menu-item.
=> add icon for new-file itme in context menu

libpeony-qt/model/side-bar-file-system-item.cpp, peony-qt-desktop/desktop-item-model.cpp
=> 解决弹出系统U盘时，会弹出光驱的问题

libpeony-qt/model/side-bar-file-system-item.cpp
Increase identifying the empty disc
=> Solving the empty disc cannot be ejected

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp, libpeony-qt/file-launcher/file-launch-action.cpp, libpeony-qt/file-launcher/file-launch-action.h, libpeony-qt/file-launcher/file-launch-manager.cpp, libpeony-qt/file-launcher/file-launch-manager.h
解决多选音频文件-右键打开选中文件时只能够打开/播放一个文件的问题
=> Solve the problem of multiple audio right-click opening exceptions

libpeony-qt/file-operation/file-delete-operation.cpp, libpeony-qt/file-operation/file-operation-manager.cpp, libpeony-qt/file-operation/file-operation-progress-bar.cpp, libpeony-qt/file-operation/file-operation-progress-bar.h
1. empty files in the recycle bin without reminding
2. Fix signale thread file operation, the pop-up box still exists after the operation was cancelled
=> fix two bugs

debian/copyright, libpeony-qt/file-info.cpp, libpeony-qt/file-info.h, libpeony-qt/model/side-bar-favorite-item.cpp, libpeony-qt/thumbnail-manager.cpp, libpeony-qt/thumbnail-manager.h, libpeony-qt/thumbnail/generic-thumbnailer.cpp, libpeony-qt/thumbnail/generic-thumbnailer.h, libpeony-qt/thumbnail/office-thumbnail.cpp, libpeony-qt/thumbnail/office-thumbnail.h, libpeony-qt/thumbnail/thumbnail.pri, libpeony-qt/thumbnail/video-thumbnail.cpp, libpeony-qt/thumbnail/video-thumbnail.h
[2] 视频文件缩略图显示的时，开发显示视频中图片的的功能
[KEYWORDS ] thumbnail
[TO SOLVE ] thumbnail
[TEST SUGGESTION] 不同格式的office文件和视频文件
[SUBMIT BY] renpeijia
[REVIEW BY]
[TEST   BY]
=>     [1] office文件缩略图显示时，开发显示首页内容的功能

peony-qt-desktop/main.cpp, src/peony-main.cpp
取消分辨率判断，解决Qt5.6版本上更改分辨率后缩放不正确问题
=> Fix: Remove resolution judgment

libpeony-qt/file-operation/file-link-operation.cpp, libpeony-qt/file-operation/file-operation-error-dialogs.cpp
=> [FIX]  slove the problem that special characters cannot be displayed

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp, libpeony-qt/file-operation/create-template-operation.cpp, libpeony-qt/file-operation/file-link-operation.cpp, libpeony-qt/windows/format_dialog.cpp, src/control/operation-menu.cpp, src/windows/main-window.cpp
=> [FIX]  creat file failure prompt error

libpeony-qt/file-operation/file-move-operation.cpp, libpeony-qt/file-operation/file-operation-error-dialog-base.cpp, libpeony-qt/file-operation/file-operation-error-dialogs.cpp, libpeony-qt/file-operation/file-operation-error-dialogs.h, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [FIX]  error pop

libpeony-qt/controls/menu/side-bar-menu/side-bar-menu.cpp, libpeony-qt/model/side-bar-abstract-item.h, libpeony-qt/model/side-bar-favorite-item.h, libpeony-qt/model/side-bar-file-system-item.cpp, libpeony-qt/model/side-bar-file-system-item.h, libpeony-qt/model/side-bar-personal-item.h, libpeony-qt/model/side-bar-separator-item.h, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> Add warning box if udisk is busy when eject udisk

libpeony-qt/model/side-bar-file-system-item.cpp, libpeony-qt/model/side-bar-file-system-item.h, libpeony-qt/model/side-bar-model.cpp
=> Update udisk info in real time after insert it.

libpeony-qt/file-utils.cpp, libpeony-qt/file-utils.h
=> Fix chinese udisk name display problem.

libpeony-qt/connect-server-dialog.cpp, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [FIX]  translation button

libpeony-qt/controls/menu/side-bar-menu/side-bar-menu.cpp
=> [FIX]  Formatting remote directories is not allowed

libpeony-qt/file-launcher/file-launch-action.cpp, libpeony-qt/libpeony-qt.pro, libpeony-qt/vfs/recent-vfs-manager.cpp, libpeony-qt/vfs/recent-vfs-manager.h, libpeony-qt/vfs/vfs.pri
[LINK] http://172.17.66.192/biz/bug-view-19161.html
在最近里添加 office 文件打開記錄
=> [FIX]  add doc to recent

libpeony-qt/file-operation/create-template-operation.cpp, libpeony-qt/file-operation/file-copy-operation.cpp, libpeony-qt/file-operation/file-delete-operation.cpp, libpeony-qt/file-operation/file-link-operation.cpp, libpeony-qt/file-operation/file-move-operation.cpp, libpeony-qt/file-operation/file-operation-error-handler.h, libpeony-qt/file-operation/file-operation-manager.cpp, libpeony-qt/file-operation/file-rename-operation.cpp, libpeony-qt/file-operation/file-trash-operation.cpp, libpeony-qt/file-operation/file-untrash-operation.cpp, libpeony-qt/file-operation/file-untrash-operation.h, libpeony-qt/thumbnail/office-thumbnail.cpp, libpeony-qt/thumbnail/video-thumbnail.cpp, libpeony-qt/thumbnail/video-thumbnail.h
FileUntrashOperation: fix bug:18260/19204.
thumnail: fix trash/recent unthumnail problem
link to: http://172.17.66.192/biz/bug-view-18260.html
http://172.17.66.192/biz/bug-view-19204.html
=>    修改回收站还原同路径同名的文件无响应的问题

libpeony-qt/vfs/recent-vfs-manager.cpp, libpeony-qt/vfs/recent-vfs-manager.h
=> add copyrigth

peony-qt-desktop/desktop-item-model.cpp
DesktopItemModel: fix Desktop refresh icon display abnormal   
link: http://172.17.66.192/biz/bug-view-20523.html
=>     解决桌面刷新，图标显示异常的问题

.github/workflows/build.yml
Related issue [ukui-control-center #787](https://github.com/ukui/ukui-control-center/pull/787)
=> Fix package conflict on Archlinux

libpeony-qt/file-operation/file-operation-error-dialogs.h, libpeony-qt/file-operation/file-operation-manager.cpp, libpeony-qt/file-operation/file-operation-progress-bar.cpp, libpeony-qt/file-operation/file-operation-progress-bar.h
[LINK] http://172.17.66.192/biz/bug-view-21810.html http://172.17.66.192/biz/bug-view-16609.html
=> [FIX]  Progress bars no longer pop up when errors occur

peony-qt-desktop/peony-desktop-application.cpp
=> Auto open dir for inserted udisk or DVD.

libpeony-qt/file-utils.cpp, peony-qt-desktop/peony-desktop-application.cpp
=> Only DvD devices are allowed to open folder automatically.

peony-qt-desktop/desktop-icon-view.cpp, peony-qt-desktop/desktop-icon-view.h
[LINK] http://172.17.66.192/biz/bug-view-19284.html
=> [FIX]  Modify resolution to rearrange desktop ICONS

libpeony-qt/controls/directory-view/delegate/icon-view-index-widget.cpp, libpeony-qt/controls/directory-view/delegate/icon-view-index-widget.h
[LINK] http://172.17.66.192/biz/bug-view-21392.html
=> [fix] Icon flickers When adjusting the window size

libpeony-qt/file-utils.h
=> Make the function public.

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp
[LINK]http://172.17.66.192/biz/bug-view-18275.html
=> [FIX]Modify resolution to not displayed of property in trash

libpeony-qt/controls/menu/side-bar-menu/side-bar-menu.cpp, libpeony-qt/model/side-bar-file-system-item.cpp, libpeony-qt/model/side-bar-file-system-item.h, libpeony-qt/model/side-bar-model.cpp, libpeony-qt/volume-manager.cpp, libpeony-qt/volume-manager.h, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> Fix eject failed problem for mobile harddisk.

libpeony-qt/file-utils.cpp, libpeony-qt/file-utils.h, peony-qt-desktop/desktop-icon-view-delegate.cpp
[LINK] http://172.17.66.192/biz/bug-view-19959.html
桌面只读文件显示小锁角标
=> [FIX]  Add lock icon for read-only files

libpeony-qt/file-utils.cpp
解决文件管理对cd名字中有特殊字符时，文件中文名字 显示乱码的问题  
link:http://172.17.66.192/biz/bug-view-22530.html
=>     fix bug: cd chinese name display error code

peony-qt-desktop/desktop-icon-view-delegate.cpp
[LINK] http://172.17.66.192/biz/bug-view-19959.html
=> [FIX]  change icon

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp
=> Fix the problem of opening multiple audio format files at the same time

libpeony-qt/model/side-bar-file-system-item.cpp, src/control/navigation-side-bar.cpp
=> The sidebar displays the DVD device in real time.

peony-qt-desktop/peony-desktop-application.cpp, peony-qt-desktop/peony-desktop-application.h
=> Fix sidebar display problem after udisk eject.

libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view-style.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.cpp, src/control/header-bar.cpp, src/control/navigation-tab-bar.cpp, src/windows/main-window.cpp, src/windows/windows.pri, src/windows/xatom-helper.cpp, src/windows/xatom-helper.h
Modified the code related to fillet and shadow, let the ukui-kwin to achieve these effects.
[FIX] some button style errors.
=> Modified the code related to fillet and shadow, let the ukui-kwin to achieve these effects.

src/windows/main-window.cpp
http://172.17.66.192/biz/bug-view-24388.html
=> Modified default transparency when kwin blur effect disabled.

libpeony-qt/file-info-job.cpp, libpeony-qt/file-info.h, libpeony-qt/file-utils.cpp, libpeony-qt/model/side-bar-file-system-item.cpp, libpeony-qt/model/side-bar-proxy-filter-sort-model.cpp, libpeony-qt/volume-manager.cpp, libpeony-qt/volume-manager.h, src/control/navigation-side-bar.cpp
=> Fix sidebar display problem when insert udisk and open gparted.

libpeony-qt/controls/directory-view/delegate/list-view-delegate.cpp, libpeony-qt/controls/directory-view/directory-view-factory/directory-view-factory-manager.cpp, libpeony-qt/controls/directory-view/directory-view-factory/icon-view-factory.h, libpeony-qt/controls/directory-view/directory-view-factory/list-view-factory.h, libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp, libpeony-qt/controls/directory-view/view/icon-view/icon-view.h, libpeony-qt/controls/directory-view/view/list-view/list-view.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.h, libpeony-qt/global-settings.cpp, libpeony-qt/model/file-item-model.cpp, libpeony-qt/model/file-item-model.h, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts, translations/peony-qt-desktop/peony-qt-desktop_cs.ts, translations/peony-qt-desktop/peony-qt-desktop_tr.ts, translations/peony-qt-desktop/peony-qt-desktop_zh_CN.ts, translations/peony-qt/peony-qt_cs.ts, translations/peony-qt/peony-qt_tr.ts, translations/peony-qt/peony-qt_zh_CN.ts
Update translations;Change the column order of list view.
Modified default window size and icon size.
=> some ui changes

libpeony-qt/file-operation/create-template-operation.cpp, libpeony-qt/file-operation/file-copy-operation.cpp, libpeony-qt/file-operation/file-move-operation.cpp, libpeony-qt/file-operation/file-rename-operation.cpp, libpeony-qt/file-operation/file-untrash-operation.cpp
[LINK] 24858 16613
名字冲突后，自动重命名
=> [FIX]  rename

libpeony-qt/controls/directory-view/delegate/list-view-delegate.cpp, libpeony-qt/controls/directory-view/delegate/list-view-delegate.h, libpeony-qt/controls/directory-view/view/list-view/list-view.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.h, src/windows/main-window.cpp
Now checkbox  on listview will move onto different column accordingly when window size changes or preview window size changes;
Remove some useless code.
=> About checkbox and fillet.

libpeony-qt/file-utils.cpp, src/peony-application.cpp
[LINK] 25455
1. 解決了执行 peony  不存在的uri，打开崩溃问题
2. 没有解决 peony  computer://root.link 类似的问题，上一个问题相对严重，用户点击可能导致崩溃，这个还不太严重
=> [FIX]  Fixed open no folder flash problem

libpeony-qt/file-utils.cpp
[LINK] ...
修复之前我引入的 peony . 无法打开的问题
添加 peony computer:///root.link uri的支持
=> [FIX]  support peony computer:///root.link

peony-qt-desktop/desktop-icon-view.cpp, peony-qt-desktop/desktop-window.cpp, src/control/header-bar.cpp
Fn + F1 will not popup help page now;
Add shortcut key for new preview action(Alt + P).
=> [FIX]The location is incorrect when press menu button in desktop;

libpeony-qt/controls/preview-page/default-preview-page/default-preview-page.cpp
bug link：http://172.17.66.192/biz/bug-view-19500.html
=>     fix bug:解决“最近”无法预览文件缩略图信息的问题

libpeony-qt/windows/format_dialog.cpp, libpeony-qt/windows/format_dialog.h
LINK 25768   http://172.17.66.192/biz/bug-view-25768.html
解决格式化启动盘，提示报错。无法挂载的现象
=> fix-disks-canot-mount-after-format

libpeony-qt/file-utils.cpp
=> Fix disk name garbled problem.

libpeony-qt/windows/format_dialog.cpp, libpeony-qt/windows/format_dialog.h, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
LINK 26066   http://172.17.66.192/biz/bug-view-26066.html
给格式化加提示 
LINK 25796   http://172.17.66.192/biz/bug-view-25796.html
U盘被占用时使其无法格式化，并加提示
=> Add advice for format and deal with format error while not umount

peony-qt-desktop/peony-json-operation.cpp
由于黑白名单的json文件格式发生变化，修改对就送文件的解析
=> 修改对json文件的解析方式

peony-qt-desktop/peony-desktop-application.cpp
=> Fix auto open problem with black cd.

libpeony-qt/file-operation/file-untrash-operation.cpp, libpeony-qt/file-operation/file-untrash-operation.h
解决的问题：
回收站还原文件的时候，遇到同名文件，选择替换，无法替换覆盖同名的文件
=> fix bug: 19204

libpeony-qt/file-operation/file-delete-operation.cpp, libpeony-qt/file-operation/file-move-operation.cpp, libpeony-qt/file-operation/file-move-operation.h, libpeony-qt/file-operation/file-node.cpp, libpeony-qt/file-operation/file-node.h
1. fix fallback move might lose files.
2. improve cancelling rollback process.
FIXME: improve undo/redo with fallback move and copy move.
=> refactor file move operation.

libpeony-qt/file-enumerator.cpp, libpeony-qt/file-enumerator.h, libpeony-qt/libpeony-qt.pro, peony-qt-desktop/peony-qt-desktop.pro, src/src.pro
添加编译选项：1、检查函数返回值
2、无用的标签
3、未初始化的变量
4、返回局部变量的地址
=>    modify:add some Compiler Options

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp, peony-qt-desktop/desktop-menu.cpp, peony-qt-desktop/user-dir-manager.cpp
Avoided the display of incorrect content in right-click menu when the templates path is wrong.
=> Fixed problems about templates path.

libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp
[ADD] Multi select mode can be enabled when selected more than one item in icon view,not just by right-click menu option.
=> About multi select mode.

libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.cpp, peony-qt-desktop/desktop-icon-view.cpp
[FIX] Move the item for a very little distance,it will pop up an annoying error massage.
=> [FIX] Move the item for a very little distance,it will pop up error massage.

libpeony-qt/controls/property-page/basic-properties-page.cpp, libpeony-qt/file-info-job.cpp, libpeony-qt/file-info.cpp, libpeony-qt/file-info.h, libpeony-qt/thumbnail-manager.cpp
allow properties page to set custom icon.
fixme: how to make custom icon be updated imdeatly?
=> [Feature] add custom icon support

debian/copyright, libpeony-qt/connect-to-server-dialog.cpp, libpeony-qt/connect-to-server-dialog.h, libpeony-qt/global-settings.cpp, libpeony-qt/global-settings.h, libpeony-qt/mount-operation.cpp, libpeony-qt/peony-core.pri, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [FIX]  Modify the user interface for login FTP

peony-qt-desktop/peony-desktop-application.cpp
=> Fix auto open problem for udisk.

libpeony-qt/model/side-bar-file-system-item.cpp, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> Fix prompt problem for unmount

libpeony-qt/controls/directory-view/delegate/list-view-delegate.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.cpp
bug link:http://172.17.66.192/biz/bug-view-26464.html
=>   fix bug: can not multi select through mouse move in list view

libpeony-qt/connect-to-server-dialog.cpp
=> change background color

libpeony-qt/controls/directory-view/view/list-view/list-view.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.h
bug link:http://172.17.66.192/biz/bug-view-26464.html
=>    fix bug: add multi select rectangle

libpeony-qt/controls/directory-view/view/list-view/list-view.cpp, peony-qt-desktop/desktop-window.cpp, peony-qt-desktop/desktop-window.h
fix bug: destop is empty when change theme in destop mirror mode
bug link:http://172.17.66.192/biz/bug-view-25703.html
=>   fix:file manager can not cancel multi sellect in listmode

libpeony-qt/file-utils.cpp, src/peony-application.cpp
note that some special directory, such as computer:///, sftp:///, favorite:///, etc, need to be handled carefully.
=> try fixing problem open window with commandline.

libpeony-qt/file-operation/file-operation-error-dialog-base.cpp, libpeony-qt/file-operation/file-operation-error-dialog-base.h, libpeony-qt/file-operation/file-operation-error-dialogs.cpp, libpeony-qt/file-operation/file-operation-error-dialogs.h, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [FIX]  Redraw the file conflict pop-up box

libpeony-qt/controls/navigation-bar/advanced-location-bar.cpp, libpeony-qt/controls/navigation-bar/advanced-location-bar.h, libpeony-qt/controls/navigation-bar/location-bar/location-bar.cpp, libpeony-qt/controls/navigation-bar/path-bar/path-edit.cpp, libpeony-qt/controls/navigation-bar/path-bar/path-edit.h, libpeony-qt/model/path-completer.cpp, src/control/header-bar.cpp, src/control/header-bar.h, src/windows/main-window.cpp
fix bug: popup can not cancel when window change max or nromal   
bug link:http://172.17.66.192/biz/bug-view-30955.html
fix bug: trash and recent name can not display in favorite
bug link:http://172.17.66.192/biz/bug-view-31534.html
=>    修改文件管理器的路径栏的两个bug

libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp, libpeony-qt/controls/directory-view/view/list-view/list-view.cpp
=> [FIX]  Remove Favorites Rename feature

src/windows/main-window.cpp
[LINK] 31123
http://172.17.66.192/biz/bug-view-31123.html
屏蔽收场夹内文件删除快捷键，删除功能以前已屏蔽
=> [FIX]  Remove the Favorites Remove feature(shotcut)

libpeony-qt/file-operation/file-operation-error-dialogs.cpp, libpeony-qt/file-operation/file-operation-error-dialogs.h, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [FIX]  Cannot cancel file operation error

libpeony-qt/connect-to-server-dialog.h, libpeony-qt/file-enumerator.cpp, libpeony-qt/mount-operation.cpp, libpeony-qt/mount-operation.h
try to resolve ftp and smb login problems, link to:
32545
31050
31033
29850
=> Remote directory

libpeony-qt/file-operation/file-operation-error-dialogs.cpp
=> [FIX]  error dialog file name

libpeony-qt/controls/menu/side-bar-menu/side-bar-menu.cpp
bug link:http://172.17.66.192/biz/bug-view-33762.html
=>    bug fix:blank CD cannot be unmount

libpeony-qt/controls/property-page/basic-properties-page-factory.cpp, libpeony-qt/controls/property-page/basic-properties-page-factory.h, libpeony-qt/controls/property-page/basic-properties-page.cpp, libpeony-qt/controls/property-page/basic-properties-page.h, libpeony-qt/controls/property-page/computer-properties-page-factory.cpp, libpeony-qt/controls/property-page/computer-properties-page-factory.h, libpeony-qt/controls/property-page/computer-properties-page.cpp, libpeony-qt/controls/property-page/computer-properties-page.h, libpeony-qt/controls/property-page/mark-properties-page-factory.cpp, libpeony-qt/controls/property-page/mark-properties-page-factory.h, libpeony-qt/controls/property-page/mark-properties-page.cpp, libpeony-qt/controls/property-page/mark-properties-page.h, libpeony-qt/controls/property-page/open-with-properties-page-factory.cpp, libpeony-qt/controls/property-page/open-with-properties-page-factory.h, libpeony-qt/controls/property-page/open-with-properties-page.cpp, libpeony-qt/controls/property-page/open-with-properties-page.h, libpeony-qt/controls/property-page/permissions-properties-page-factory.cpp, libpeony-qt/controls/property-page/permissions-properties-page-factory.h, libpeony-qt/controls/property-page/permissions-properties-page.cpp, libpeony-qt/controls/property-page/permissions-properties-page.h, libpeony-qt/controls/property-page/property-page.pri, libpeony-qt/controls/property-page/recent-and-trash-properties-page-factory.cpp, libpeony-qt/controls/property-page/recent-and-trash-properties-page-factory.h, libpeony-qt/controls/property-page/recent-and-trash-properties-page.cpp, libpeony-qt/controls/property-page/recent-and-trash-properties-page.h, libpeony-qt/windows/properties-window.cpp, libpeony-qt/windows/properties-window.h, plugin-iface/plugin-iface.pri, plugin-iface/properties-window-tab-iface.h, plugin-iface/properties-window-tab-page-plugin-iface.h
新增:
1.新增文件打开方式页面。
2.修改标记Tab页面部分错误代码。
3.basic页面添加打开方式切换功能。
解决:
1.去除各个页面的表格边框
2.TAB页API名称已更改
3.昨天的部分问题已更改
=> rebuild properties-window 

libpeony-qt/file-utils.cpp, libpeony-qt/file-utils.h, libpeony-qt/model/file-item-proxy-filter-sort-model.cpp, libpeony-qt/model/file-item.cpp, libpeony-qt/model/file-item.h
=> Fix device item problem for empty drive.

libpeony-qt/model/file-item-model.cpp, libpeony-qt/thumbnail-manager.cpp, peony-qt-desktop/desktop-item-model.cpp, src/control/tab-widget.cpp
bug link:http://172.17.66.192/biz/bug-view-31190.html
bug fix: preview can not update,when dir changes
bug link:http://172.17.66.192/biz/bug-view-33923.html
=>    bug fix:the desktop file in trash can not show normal icon

libpeony-qt/controls/menu/menu-plugin-manager.cpp
=> [FIX]  [MTP] Sending shortcut cannot be opened

libpeony-qt/controls/navigation-bar/location-bar/location-bar.cpp, libpeony-qt/file-info.cpp, libpeony-qt/file-info.h
=> Fix chinese display name garbled problem.

libpeony-qt/windows/properties-window.cpp, libpeony-qt/windows/properties-window.h, peony-qt-desktop/desktop-menu.cpp
详细请看：http://172.17.66.192/biz/task-view-17809.html
方案：分别打开各个窗口。
2.优化部分代码风格
=> Fix BUG:#17809

peony-qt-desktop/peony-desktop-application.cpp
=> Fix audio cd auto open problem.

src/control/tab-widget.cpp
=> Fix trash:/// display problem after eject udisk.

libpeony-qt/model/side-bar-file-system-item.cpp
=> Fix udisk empty icon problem for sidebar

libpeony-qt/file-operation/file-operation-error-dialogs.cpp
=> [FIX]  cannot click backup button

libpeony-qt/controls/property-page/basic-properties-page-factory.cpp, libpeony-qt/controls/property-page/basic-properties-page.cpp, libpeony-qt/controls/property-page/basic-properties-page.h, libpeony-qt/controls/property-page/details-properties-page.cpp, libpeony-qt/controls/property-page/open-with-properties-page-factory.cpp, libpeony-qt/controls/property-page/open-with-properties-page.cpp, libpeony-qt/controls/property-page/open-with-properties-page.h, libpeony-qt/controls/property-page/permissions-properties-page.cpp, libpeony-qt/controls/property-page/permissions-properties-page.h, libpeony-qt/controls/property-page/recent-and-trash-properties-page.cpp, libpeony-qt/controls/property-page/recent-and-trash-properties-page.h, libpeony-qt/windows/properties-window.cpp
1.修改basic页部分UI。
2.在不可修改名称的文件夹上屏蔽隐藏按钮，改名框和移动按钮。
3.修复在同时改名和隐藏文件的情况下peony崩溃的问题。
4.修复在peony中右键计算机打开属性窗口时窗口崩溃的问题。
5.增加日期格式跟随系统改变。
6.使用elide方式处理部分文字。
7.权限页添加可执行选项
open With tab 页
1.增加选择其他打开方式功能。
2.加入多线程支持。
3.更新翻译。
修复：#37619
=> fix some bugs

src/windows/about-dialog.cpp
=> [FIX] about closeBtn repair

libpeony-qt/controls/property-page/basic-properties-page.cpp, libpeony-qt/controls/property-page/mark-properties-page.cpp, libpeony-qt/controls/property-page/open-with-properties-page.cpp, libpeony-qt/controls/property-page/permissions-properties-page.cpp
1.解决：#37718 收藏夹中打开文件夹的属性与实际的不一致。
2.文件夹属性不再统计本身。
=> Fix properties window bugs

libpeony-qt/windows/properties-window.cpp
=> fix properties window ui

libpeony-qt/file-launcher/file-launch-manager.cpp
bug link:http://172.17.66.192/biz/bug-view-36366.html
=>    bug fix: get wrong default app for avi file

libpeony-qt/file-info.cpp
=> Fix default name garbled problem for udisk.

libpeony-qt/connect-to-server-dialog.cpp
=> [FIX]  save password

libpeony-qt/model/side-bar-file-system-item.cpp, libpeony-qt/model/side-bar-file-system-item.h, libpeony-qt/peony-core.pri, libpeony-qt/sync-thread.cpp, libpeony-qt/sync-thread.h, translations/libpeony-qt/libpeony-qt_cs.ts, translations/libpeony-qt/libpeony-qt_tr.ts, translations/libpeony-qt/libpeony-qt_zh_CN.ts
=> [Fix] sync data before eject or unmount.

libpeony-qt/controls/property-page/recent-and-trash-properties-page.cpp, libpeony-qt/file-operation/file-operation-manager.cpp
using trash property page to control wether trash operation should be confirmed.
=> FileOperationManager: add comfirm trash dialog option. link to: #26062

peony-qt-desktop/peony-desktop-application.cpp, peony-qt-desktop/peony-qt-desktop.pro, peony-qt-desktop/primary-manager.cpp, peony-qt-desktop/primary-manager.h
adapt for ukui wayland session
=> Wayland primary screen

libpeony-qt/controls/property-page/details-properties-page.cpp, libpeony-qt/controls/property-page/details-properties-page.h
bug link:http://172.17.66.192/biz/bug-view-38094.html
=>    bug fix:add tooltip function in details properties page for location

libpeony-qt/controls/property-page/details-properties-page.cpp, libpeony-qt/controls/property-page/details-properties-page.h, libpeony-qt/windows/properties-window.cpp
bug link:http://172.17.66.192/biz/bug-view-40457.html
bug fix:the full name of file can not display, when it is too long.
bug link:http://172.17.66.192/biz/bug-view-37629.html
=>    bug fix: the icon of desktop can not dispay in title.

libpeony-qt/controls/property-page/basic-properties-page.cpp, libpeony-qt/controls/property-page/basic-properties-page.h
bug link:http://172.17.66.192/biz/bug-view-40487.html
=>    bug fix:the icon of property is not update, when it changes.

libpeony-qt/controls/property-page/basic-properties-page.cpp, libpeony-qt/file-utils.cpp, libpeony-qt/file-utils.h
[LINK]
修复 NTFS 文件系统无法显示文件创建时间的问题
=> [FIX]  ntfs filesystem's document cannot display create time
