ukui/peony

configure.ac

They are actually dependencies of libegg. Without the checking the
configure step completes successfully but "make" ends up in errors about
these missing libraries.

Add check for libSM and libICE

---

peony-qt-desktop/desktop-menu.cpp

fix #14. Right click on the desktop,  when the menu is a background menu just don't add "propertries" action.

When it's a background menu, hide the "propertries" action in the menu 

---

libpeony-qt/file-operation/file-operation-error-dialog.cpp

Copy same file to desktop twice(#50), it should call FileOperationErrorDialog to show error info. but when FileOperationProgressWizard showed, it cause previous dialog flashed once.
Even though FileOperationErrorDialog only show once but it looks like this dialog have showed twice. We should use WindowStaysOnTopHint to make sure this dialog show on top to avoid this problem.

copy same file to desktop twice, error report dialog show twice

---

libpeony-qt/model/file-item.cpp

when change file content and close file(#69). FileItem::onChildAdded was called. m_model may already have this child, but  the child info may be changeed. So child info need to update.

fix change file content and close file, file info is not update in list view

---

libpeony-qt/controls/directory-view/view/list-view/list-view.cpp

Add clearSelection() in the ListView::mousePressEvent() can slove this problem(#92).
And the reason why I add clearFocus() in ListView2::bindModel() is if I don't add this function then when I do this: 1.click an item; 2. click blank space; 3. click another item. The first item will be included in a dotted box while the menu pop up near the second item.

if click left button at blank space, it should select nothing

---

libpeony-qt/controls/directory-view/delegate/icon-view-index-widget.cpp
libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp
libpeony-qt/controls/directory-view/view/icon-view/icon-view.h
libpeony-qt/controls/directory-view/view/list-view/list-view.cpp
libpeony-qt/controls/directory-view/view/list-view/list-view.h

fix rename issue(#19,#79,#84). Delete old edit timer and click timer, using renamer instead. When a moursePressEvent happened, check m_renameTimer first. If m_renameTimer's remaining Time fit the range [750, 3000], then trigger rename slot.
when a rename request triggered, let another timer in rename slot do a delay for waiting some events performed, such as doubleclick and drag. After check edit if valid, then decide if edit event really happen.

fix rename issue. drop old time trigger and use QTimer::remainingTime()

---

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp
libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.h

屏蔽光盘里直接创建文件功能。
burn://开头的文件是放在内存里的，不能编辑

Mask the new button on the CD

---

libpeony-qt/file-operation/file-operation-progress-wizard.cpp
libpeony-qt/file-operation/file-operation-progress-wizard.h

bug id: 13999
当大量文件移动过程中，点击文件移动进度指示框的关闭按钮时候，文件移动进度指示框会在系统托盘中最小化显示，同时弹出提醒框。此bug就是提醒框先显示在屏幕最左上角一次，然后才能在正确的位置显示。已修复！

fix tip popup position

---

peony-qt-desktop/desktop-icon-view.cpp

fix  bug14467 ,  shortcut cannot open . because the qt-version is lower than x86 ,  uri contain space case the problem.

fix desktop shortcut cannot be opened in arm

---

libpeony-qt/file-operation/file-copy-operation.cpp
libpeony-qt/file-operation/file-operation-error-dialogs.cpp

[LINK] 19193
磁盘空间满时候，再进行连续复制文件操作就会出现这个问题

[FIX]  When you copy a file, the probability is infinite copy

---

libpeony-qt/file-operation/file-copy-operation.cpp
libpeony-qt/file-operation/file-move-operation.cpp
libpeony-qt/file-operation/file-operation-progress-bar.cpp

[LINK] 19771
解決进度条文件名闪烁问题，现在进度条只显示传输中的文件，不会再显示传输到的目标文件夹，减少了频繁切换造成的闪烁视觉

[FIX]  Resolved progress bar name flashing during file copying or moving

---

libpeony-qt/file-operation/file-operation-manager.cpp
libpeony-qt/file-operation/file-operation-manager.h
libpeony-qt/file-operation/file-untrash-operation.cpp

FileOperation: fix undo/redo operation of untrash and link.
自测结果：
1、createTemplateOperation不支持 undo/redo的操作，因为该流程不通过Fileoperationmanager执行，设计如此；
2、filecopy操作支持undo/redo功能；
3、filedelete操作不支持undo/redo功能，设计如此；
4、file link支持undo/redo功能，此次修改内容；
5、filemove操作不出错（文件冲突或者其他错误）时，支持undo/redo操作，而且当出现文件冲突时，move操作变成了copy操作，设计如此；
6、filerename操作，支持undo/redo功能。
7、trash测试支持undo/redo操作，但是在回收站中存在多个不同原路径的同名文件的时候，undo/redo操作有问题，有待改善；
8、untrash操作的undo/redo操作支持（此次修改内容），但是当还原多个文件的时候不支持，在FileOperationUtils做了限制，设计如此。

修改untrash和link操作的undo/redo功能

---

peony-qt-desktop/desktop-icon-view-delegate.cpp
peony-qt-desktop/desktop-icon-view.cpp

[LINK] http://172.17.66.192/biz/bug-view-19994.html
桌面图标名字显示两行

[FIX]  The icon name displays two lines

---

libpeony-qt/windows/format_dialog.cpp
libpeony-qt/windows/format_dialog.ui

1.limited the format name length in 11.
2.slove the name cannot save while input the format name over 8

limited the max length of format name

---

libpeony-qt/file-operation/file-operation-progress-bar.cpp

[LINK] http://172.17.66.192/biz/bug-view-21252.html
不允許並行文件操作，取消操作文件崩潰問題

[FIX]  Parallel operation is not allowed to cancel file operation crash

---

libpeony-qt/controls/directory-view/delegate/icon-view-index-widget.cpp
libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp
peony-qt-desktop/desktop-icon-view.cpp
peony-qt-desktop/desktop-index-widget.cpp
src/windows/main-window.cpp

[FIX] Double click can not trigger launch event.
[FIX] Desktop icon flicker when style switching.#22702
Let transparency can be adjusted while blur effect was disabled.

Fixed a few problems

---

debian/copyright
libpeony-qt/file-info-job.cpp
libpeony-qt/file-info.h
peony-qt-desktop/bw-list-info.cpp
peony-qt-desktop/bw-list-info.h
peony-qt-desktop/desktop-icon-view.cpp
peony-qt-desktop/desktop-icon-view.h
peony-qt-desktop/desktop-item-proxy-model.cpp
peony-qt-desktop/desktop-item-proxy-model.h
peony-qt-desktop/peony-dbus-service.cpp
peony-qt-desktop/peony-dbus-service.h
peony-qt-desktop/peony-json-operation.cpp
peony-qt-desktop/peony-json-operation.h
peony-qt-desktop/peony-qt-desktop.pro

1、当设置黑名单时，黑名单的desktop文件不在桌面显示
2、当设置白名单时，桌面只显示白名单中的desktop文件
3、当设置成正常莫模式时，不对desktop文件进行过滤，所有的desktop文件都会显示在桌面
自测用例：
1、对黑名单模式、白名单模式和正常模式，进行通过dbus接口通知桌面更新以及系统重启测试；
2、当配置文件不存在时，通过dbus接口通知桌面更新以及系统重启测试；
3、当配置文件为空时，通过dbus接口通知桌面更新以及系统重启测试；
4、当黑白名单为空的时候，对黑名单模式、白名单模式和正常模式，进行通过dbus接口通知桌面更新以及系统重启测试；

给桌面添加黑白名单功能

---

libpeony-qt/controls/preview-page/default-preview-page/default-preview-page.cpp
libpeony-qt/controls/property-page/basic-properties-page.cpp
libpeony-qt/controls/property-page/computer-properties-page.cpp
libpeony-qt/controls/status-bar/status-bar.cpp
libpeony-qt/file-info-job.cpp
libpeony-qt/file-operation/file-operation-progress-bar.cpp
libpeony-qt/file-operation/file-operation-progress-wizard.cpp
libpeony-qt/windows/format_dialog.cpp
src/control/tab-status-bar.cpp

link [22695] 电脑U盘大小和终端显示的大小不一致
修改了计算磁盘大小的方式 以1024来计算，使得终端显示的大小和查看的大小一致(四舍五入）

Calculated disk size by 1024 bytes

---

peony-qt-desktop/peony-desktop-application.cpp
src/control/navigation-side-bar.cpp

link[25768]   peony-qt-desktop/peony-desktop-application.cpp
卸载u盘  会移除U盘导致格式化是无法检测到设备，先屏蔽等闫焕章在处理移除功能
http://172.17.66.192/biz/bug-view-25768.html
link[25425]  http://172.17.66.192/biz/bug-view-25425.html
src/control/navigation-side-bar.cpp
格式化U盘两次侧边栏无法显示问题

slove-format-twice-canot-display-in_sidebar-And-format-error

---

libpeony-qt/file-operation/file-operation-progress-bar.cpp
libpeony-qt/file-operation/file-operation-progress-bar.h

[LINK] 27362
文件操作过程中，文件名太长则自动换行（最多换行显示三行）

[FIX]  Filenames are too long to wrap automatically

---

libpeony-qt/controls/menu/directory-view-menu/directory-view-menu.cpp
libpeony-qt/convenient-utils/clipboard-utils.cpp
libpeony-qt/file-launcher/file-launch-action.cpp
src/windows/main-window.cpp

[FIX]Uri problems when open file in recent dir.
Now files in recent dir can be copied correctly,besids,cut operation is banned and delete operation is aimed at the record itself.

About file operation in recent dir.

---

libpeony-qt/model/side-bar-file-system-item.cpp
libpeony-qt/model/side-bar-model.cpp

1.sidebar eject-button show problem.
2.after close gparted,some of the partition names are confusing.

Fix two known problems

---

peony-qt-desktop/desktop-item-model.cpp

bug link:http://172.17.66.192/biz/bug-view-29417.html
问题：当拖拽文件到桌面的时候，会落到第二列，而不是落在第一列
原因：处理拖拽文件坐标的时候，边界值处理不对

    fix bug: the location is wrong, when drag and drop file to desktop

---

libpeony-qt/file-operation/file-operation-error-dialogs.cpp
libpeony-qt/file-operation/file-operation-error-dialogs.h

[LINK]
解决点击，备份全部、忽略全部、替换全部，无法生效的问题，主要原因是checkbox监听事件错误导致。

[FIX]  backup all

---

libpeony-qt/bookmark-manager.cpp

[LINK] update favorite after delete directory
17814 | 一般 | 桌面V10.1通用版 | 【文件管理器】已删除的文件夹在收藏夹不能及时更新

[FIX]  17814

---

libpeony-qt/controls/directory-view/view/icon-view/icon-view.cpp
libpeony-qt/controls/directory-view/view/list-view/list-view.cpp
libpeony-qt/model/file-item-model.cpp
libpeony-qt/model/file-item-model.h
libpeony-qt/model/side-bar-model.cpp
libpeony-qt/model/side-bar-model.h
peony-qt-desktop/desktop-icon-view.cpp
peony-qt-desktop/desktop-icon-view.h
peony-qt-desktop/desktop-item-model.cpp
peony-qt-desktop/desktop-item-model.h
src/control/navigation-side-bar.cpp

models: change default drag and drop action as move action.
note that qt asumes copy action as default drop action in model/view desgin. that let the dnd action is offen misunterstanded by people.
so we reimplement it in peony. link to #25917.

DesktopIconView: reimplement startDrag() method.

---

libpeony-qt/file-info-job.cpp
libpeony-qt/file-info-job.h
libpeony-qt/file-info.h
libpeony-qt/file-operation/file-copy-operation.cpp
libpeony-qt/file-operation/file-move-operation.cpp
libpeony-qt/file-operation/file-operation.cpp
libpeony-qt/file-operation/file-operation.h

[LINK] 38545
针对 fat、ntfs 等不支持特殊符号的 文件系统，在文件操作时候做了特殊处理

[FIX]  Copy file name with time to USB drive, copy failed

---

libpeony-qt/controls/property-page/open-with-properties-page.cpp
libpeony-qt/controls/property-page/recent-and-trash-properties-page.cpp
libpeony-qt/windows/format_dialog.cpp
libpeony-qt/windows/format_dialog.ui
peony-qt-desktop/desktop-icon-view.cpp
peony-qt-desktop/desktop-menu.cpp
peony-qt-desktop/desktop-window.cpp
peony-qt-desktop/desktop-window.h
peony-qt-desktop/main.cpp
peony-qt-desktop/peony-desktop-application.cpp
peony-qt-desktop/peony-qt-desktop.pro
peony-qt-desktop/plasma-shell-manager.cpp
peony-qt-desktop/plasma-shell-manager.h
peony-qt-desktop/primary-manager.cpp
peony-qt-desktop/primary-manager.h
src/control/tab-widget.cpp
translations/peony-qt-desktop/peony-qt-desktop_cs.ts
translations/peony-qt-desktop/peony-qt-desktop_tr.ts
translations/peony-qt-desktop/peony-qt-desktop_zh_CN.ts

重构桌面：
1、增加对于wayland平台的适配
2、增加virtualDesktopWindow，所有的desktop window都作为它的子窗口进行显示
3、将desktop icon view从desktop window解绑并绑定virtual desktop window，置于顶端（解决桌面图标消失、背景存在的问题）
4、优化与panel位置的交互代码
其它问题：
1、修复gio critical（右键菜单偶发崩溃问题）
2、目前对于wayland适配有一个bug，wayland下弹出菜单有问题，只能在一个屏幕中弹出，无法超过这个屏幕范围，切换主屏问题依旧，暂时没有解决的头绪
review建议：
主要关注屏幕插拔，主屏改变，旋转屏幕，分辨率改变等屏幕操作是否有bug

Refactor desktop
